import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  Locale _currentLocale = const Locale('ar');

  Locale get currentLocale => _currentLocale;
  Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'PrettyPlan',
      'welcome': 'Welcome',
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'logout': 'Logout',
      'name_required': 'Name is required',
      'email_required': 'Email is required',
      'invalid_email': 'Invalid email',
      'password_required': 'Password is required',
      'password_too_short': 'Password too short',
      'passwords_do_not_match': 'Passwords do not match',
      'already_have_account': 'Already have an account? Login',
      'need_account': 'Need an account? Register',
      'add_task': 'Add New Task',
      'task_title': 'Task Title',
      'note': 'Note',
      'reward_amount': 'Reward Amount',
      'enter_title': 'Please enter a title',
      'enter_amount': 'Please enter an amount',
      'invalid_amount': 'Invalid amount',
      'priority': 'Priority',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'deadline_date': 'Deadline Date',
      'deadline_time': 'Deadline Time',
      'cancel': 'Cancel',
      'task_failed': 'Failed to add task',
      'admin_panel': 'Admin Panel',
      'balance': 'Balance',
      'pretty_plan': 'PrettyPlan',
      'sort_by': 'Sort by',
      'date': 'Date',
      'no_tasks_found': 'No tasks found',
      'priority_': 'Priority: ',
      'deadline': 'Deadline',
      'reward': 'Reward',
      'category_all': 'All',
      'category_family': 'Family',
      'category_personal': 'Personal',
      'category_job': 'Job',
      'category_another': 'Another',
      'tab_tasks': 'Tasks',
      'tab_withdrawals': 'Withdrawals',
      'loading': 'Loading...',
      'dialog_mark_completed_title': 'Mark as Completed?',
      'dialog_mark_completed_content':
          'Do you want to mark this task as completed?',
      'button_cancel': 'Cancel',
      'button_yes': 'Yes',
      'label_deadline': 'Deadline',
      'label_reward': 'Reward',
      'label_requested': 'Requested',
      'Enter Transaction Number': 'Enter Transaction Number',
      'Transaction #': 'Transaction #',
      'withdrawal_history': 'Withdrawal History',
      'no_withdrawal_history': 'No withdrawal history yet',
      'transfer_number': 'Transfer Number',
      'requested_on': 'Requested on',
      'withdraw': 'Withdraw',
      'history': 'History',
      'withdraw_success': 'Withdraw request has submitted',
      'withdraw_failed': 'Failed to submit withdraw request',
      'enter_withdrawal_amount': 'Enter Withdrawal Amount',
      'your_current_balance': 'Your current balance',
      'amount': 'Amount',
      'please_enter_amount': 'Please enter an amount',
      'invalid_number': 'Enter a valid number',
      'amount_greater_than_zero': 'Amount must be greater than zero',
      'amount_exceeds_balance': 'Amount exceeds your balance',
      'withdraw_now': 'Withdraw Now',
      'Logged in successfully': 'Logged in successfully',
      'Registered successfully': 'Registered successfully',
      "Rejected": 'Rejected',
      'Approved': 'Approved',
      'pending': 'Pending',
      'status_in_progress': 'Click here if done',
      'status_pending': 'Under Review',
      'status_completed': 'Completed',
      'statuss_in_progress': 'Sent',
      'statuss_pending': 'Under Review',
      'statuss_completed': 'Completed',
      'status_unknown': 'Unknown',
      'priority_low': 'Low',
      'priority_medium': 'Medium',
      'priority_high': 'High',
      'status_approved': 'Approved',
      'status_rejected': 'Rejected',
      "category": "Category",
      "all": "All",
      "family": "Family",
      "personal": "Personal",
      "job": "Job",
      "another": "Another",
      'task_added':'The task has been added successfully'
    },
    'ar': {
      'app_name': 'بريتي بلان',
      'welcome': 'مرحبًا',
      'welcome_back': 'مرحبًا مرة أخرى',
      'create_account': 'إنشاء حساب',
      'login': 'تسجيل الدخول',
      'register': 'تسجيل',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'full_name': 'الاسم الكامل',
      'logout': 'تسجيل الخروج',
      'name_required': 'الاسم مطلوب',
      'email_required': 'البريد الإلكتروني مطلوب',
      'invalid_email': 'البريد الإلكتروني غير صالح',
      'password_required': 'كلمة المرور مطلوبة',
      'password_too_short': 'كلمة المرور قصيرة جدًا',
      'passwords_do_not_match': 'كلمات المرور غير متطابقة',
      'already_have_account': 'هل لديك حساب؟ تسجيل الدخول',
      'need_account': 'هل تحتاج إلى حساب؟ تسجيل',
      'add_task': 'إضافة مهمة جديدة',
      'task_title': 'عنوان المهمة',
      'note': 'ملاحظة',
      'reward_amount': 'قيمة المكافأة',
      'enter_title': 'يرجى إدخال العنوان',
      'enter_amount': 'يرجى إدخال المبلغ',
      'invalid_amount': 'مبلغ غير صالح',
      'priority': 'الأولوية',
      'low': 'منخفضة',
      'medium': 'متوسطة',
      'high': 'مرتفعة',
      'deadline_date': 'تاريخ التسليم',
      'deadline_time': 'وقت التسليم',
      'cancel': 'إلغاء',
      'task_failed': 'فشل في إضافة المهمة',
      'admin_panel': 'لوحة التحكم',
      'balance': 'الرصيد',
      'pretty_plan': 'بريتي بلان',
      'sort_by': 'ترتيب حسب',
      'date': 'التاريخ',
      'no_tasks_found': 'لا توجد مهام',
      'priority_': 'الأولوية: ',
      'deadline': 'الموعد النهائي',
      'reward': 'المكافأة',
      'category_all': 'الكل',
      'category_family': 'العائلة',
      'category_personal': 'شخصي',
      'category_job': 'العمل',
      'category_another': 'أخرى',
      'tab_tasks': 'المهام',
      'tab_withdrawals': 'طلبات السحب',
      'loading': 'جاري التحميل...',
      'dialog_mark_completed_title': 'وضع علامة مكتمل؟',
      'dialog_mark_completed_content':
          'هل تريد وضع علامة "مكتمل" على هذه المهمة؟',
      'button_cancel': 'إلغاء',
      'button_yes': 'نعم',
      'label_deadline': 'الموعد النهائي',
      'label_reward': 'المكافأة',
      'label_requested': 'تم الطلب في',
      'Enter Transaction Number': 'أدخل رقم المعاملة',
      'Transaction #': 'رقم المعاملة',
      'withdrawal_history': 'سجل السحب',
      'no_withdrawal_history': 'لا يوجد سجل سحب بعد',
      'transfer_number': 'رقم التحويل',
      'requested_on': 'تم الطلب في',
      'withdraw': 'سحب',
      'history': 'السجل',
      'withdraw_success': 'تم إرسال طلب السحب بقيمة ',
      'withdraw_failed': 'فشل في إرسال طلب السحب',
      'enter_withdrawal_amount': 'أدخل مبلغ السحب',
      'your_current_balance': 'رصيدك الحالي',
      'amount': 'المبلغ',
      'please_enter_amount': 'يرجى إدخال المبلغ',
      'invalid_number': 'أدخل رقمًا صحيحًا',
      'amount_greater_than_zero': 'يجب أن يكون المبلغ أكبر من صفر',
      'amount_exceeds_balance': 'المبلغ يتجاوز رصيدك',
      'withdraw_now': 'اسحب الآن',
      'Registered successfully': 'تم التسجيل بنجاح',
      "Logged in successfully": 'تم تسجيل الدخول بنجاح',
      "Rejected": 'مرفوض',
      'Approved': 'تمت الموافقة',
      'pending': 'قيد الانتظار',
      'priority_low': 'منخفض',
      'priority_medium': 'متوسط',
      'priority_high': 'مرتفع',
      'status_in_progress': 'اضغط هنا إذا تم الإنجاز',
      'status_pending': 'قيد المراجعة',
      'status_completed': 'مكتمل',
      'status_unknown': 'غير معروف',
      'status_approved': 'موافق عليه',
      'status_rejected': 'مرفوض',
      'statuss_in_progress': 'مرسلة',
      'statuss_pending': 'قيد المراجعة',
      'statuss_completed': 'مكتمل',
      "category": "الفئة",
      "all": "الكل",
      "family": "العائلة",
      "personal": "شخصي",
      "job": "العمل",
      "another": "أخرى",
      'task_added':'تم اضافة المهمة بنجاح'
    },
  };
  TextDirection get textDirection =>
      _currentLocale == 'ar' ? TextDirection.ltr : TextDirection.rtl;

  void changeLanguage(String langCode) {
    _currentLocale = Locale(langCode);
    notifyListeners();
  }

  String translate(String key) {
    return translations[_currentLocale.languageCode]?[key] ?? key;
  }

  bool isArabic() => _currentLocale.languageCode == 'ar';
}
